from .items import *

INVENTORY_MAP = {
    SWORD: "01",
    BOMB: "02",
    POWER_BRACELET: "03",
    SHIELD: "04",
    BOW: "05",
    HOOKSHOT: "06",
    MAGIC_ROD: "07",
    PEGASUS_BOOTS: "08",
    OCARINA: "09",
    FEATHER: "0A",
    SHOVEL: "0B",
    MAGIC_POWDER: "0C",
    BOOMERANG: "0D",
}
INVENTORY_ICON = {
    SWORD: "84",
    BOMB: "80",
    POWER_BRACELET: "82",
    SHIELD: "86",
    BOW: "88",
    HOOKSHOT: "8A",
    MAGIC_ROD: "8C",
    PEGASUS_BOOTS: "98",
    OCARINA: "90",
    FEATHER: "92",
    SHOVEL: "96",
    MAGIC_POWDER: "8E",
    BOOMERANG: "A4",
}
INVENTORY_NAME = {
    SWORD: b"Sword",
    BOMB: b"Bombs",
    POWER_BRACELET: b"Power Bracelet",
    SHIELD: b"Shield",
    BOW: b"Bow",
    HOOKSHOT: b"Hookshot",
    MAGIC_ROD: b"Magic Rod",
    PEGASUS_BOOTS: b"Pegasus Boots",
    OCARINA: b"Ocarina",
    FEATHER: b"Roc's Feather",
    SHOVEL: b"Shovel",
    MAGIC_POWDER: b"Magic Powder",
    BOOMERANG: b"Boomerang",
}
CHEST_ITEMS = {
    POWER_BRACELET: 0x00,
    SHIELD: 0x01,
    BOW: 0x02,
    HOOKSHOT: 0x03,
    MAGIC_ROD: 0x04,
    PEGASUS_BOOTS: 0x05,
    OCARINA: 0x06,
    FEATHER: 0x07, SHOVEL: 0x08, MAGIC_POWDER: 0x09, BOMB: 0x0A, SWORD: 0x0B, FLIPPERS: 0x0C,
    MAGNIFYING_LENS: 0x0D, MEDICINE: 0x10,
    TAIL_KEY: 0x11, ANGLER_KEY: 0x12, FACE_KEY: 0x13, BIRD_KEY: 0x14, GOLD_LEAF: 0x15,
    RUPEES_50: 0x1B, RUPEES_20: 0x1C, RUPEES_100: 0x1D, RUPEES_200: 0x1E, RUPEES_500: 0x1F,
    SEASHELL: 0x20, MESSAGE: 0x21, GEL: 0x22,
    MAP: 0x16, COMPASS: 0x17, STONE_BEAK: 0x18, NIGHTMARE_KEY: 0x19, KEY: 0x1A,

    BOOMERANG: 0x0E,
    SLIME_KEY: 0x0F,
}
