name: Compare logic against previous commit

on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'   # excludes master

permissions:
  contents: read

jobs:
  run-tester:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - run: chmod +x compare-logic.sh
    - run: ./compare-logic.sh
    - name: Upload result
      uses: actions/upload-artifact@v4
      with:
        name: differences.log
        path: './LogicTester/diffs.log'