name: Build multiworld client

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U pyinstaller
        pip install -U flask
    - name: Install pyevilemu
      run: |
        git clone https://github.com/daid/pyevilemu.git
        cd pyevilemu
        python setup.py install
    - name: Build with pyinstaller
      run: |
        cd multiworld
        pyinstaller --clean -y client.py -n multiworldclient
    - name: Upload windows dist build
      uses: actions/upload-artifact@v3
      with:
        name: multiworld-client-windows
        path: multiworld/dist/multiworldclient
