name: Python parse test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - run: python3 main.py -h
    - run: python3 main.py SKIP_ROM_GENERATION --timeout 120 --output /dev/null
    - run: python3 main.py SKIP_ROM_GENERATION --timeout 120 -s seashells=0 -s heartpiece=0 -s dungeon_items=keysanity --output /dev/null
    - run: python3 main.py SKIP_ROM_GENERATION --timeout 120 -s logic=glitched -s dungeon_items=keysanity -s heartpiece=0 -s seashells=0 -s heartcontainers=0 -s instruments=1 -s owlstatues=both -s dungeonshuffle=1 -s witch=0 -s boomerang=gift -s steal=never -s goal=random --output /dev/null
    - run: python3 main.py SKIP_ROM_GENERATION --timeout 120 -s logic=casual -s dungeon_items=keysy -s itempool=casual --output /dev/null
    - run: python3 main.py SKIP_ROM_GENERATION --timeout 120 -s textmode=none --output /dev/null
    - run: python3 main.py SKIP_ROM_GENERATION --timeout 120 -s overworld=dungeondive --output /dev/null
    - run: python3 main.py SKIP_ROM_GENERATION --timeout 120 -s overworld=nodungeons --output /dev/null
    - run: python3 main.py SKIP_ROM_GENERATION --timeout 120 -s overworld=alttp --output /dev/null
    - run: python3 main.py SKIP_ROM_GENERATION --timeout 120 -s overworld=dungeonchain --output /dev/null
    - run: python3 main.py SKIP_ROM_GENERATION --timeout 120 -s owlstatues=dungeon --output /dev/null
    - run: python3 main.py SKIP_ROM_GENERATION --timeout 120 -s owlstatues=overworld --output /dev/null
    - run: python3 main.py SKIP_ROM_GENERATION --timeout 120 -s owlstatues=both --output /dev/null
    - run: python3 main.py SKIP_ROM_GENERATION --timeout 120 -s randomstartlocation=1 --output /dev/null
    - run: python3 main.py SKIP_ROM_GENERATION --timeout 120 -s dungeonshuffle=1 --output /dev/null
    - run: python3 main.py SKIP_ROM_GENERATION --timeout 120 -s entranceshuffle=simple --output /dev/null
    - run: python3 main.py SKIP_ROM_GENERATION --timeout 120 -s entranceshuffle=split --output /dev/null
    - run: python3 main.py SKIP_ROM_GENERATION --timeout 120 -s entranceshuffle=mixed --output /dev/null
    - run: python3 main.py SKIP_ROM_GENERATION --timeout 120 -s entranceshuffle=wild --output /dev/null
    - run: python3 main.py SKIP_ROM_GENERATION --timeout 120 -s entranceshuffle=chaos --output /dev/null
    - run: python3 main.py SKIP_ROM_GENERATION --timeout 120 -s entranceshuffle=insane --output /dev/null
    - run: python3 main.py SKIP_ROM_GENERATION --timeout 120 -s entranceshuffle=madness --output /dev/null
    - run: python3 main.py SKIP_ROM_GENERATION --timeout 120 -s entranceshuffle=madness -s shufflejunk=1 -s shuffleannoying=1 -s shufflewater=1 --output /dev/null
    - run: python3 main.py SKIP_ROM_GENERATION --timeout 120 -s boss=random --output /dev/null
    - run: python3 main.py SKIP_ROM_GENERATION --timeout 120 -s miniboss=random --output /dev/null
